### PR TITLE
Fix to support iOS 8.4 (tested with Unity version 5.1.3f1)

### PR DESCRIPTION
**Pull request by haxpor**
Fixed via the following
- Override (void)willStartWithViewController method instead of using createViewHierarchyImpl which is marked as deprecated.
- Changed project setting in Unity project to auto rotate (See in PlayerSetting window) but limit to only in Portrait orientation.
- Added instructions needed to do after exporting Xcode project from Unity to make it works with latest iOS.

### CODE REVIEW

**Comment by haxpor** [comment]
One thing I'm still unsure on how to fix: `UnityPause()`. I have to comment it out in code that wrapped by #ifndef __cplusplus. It might be something about syntax.

**Comment by samizzo** [comment]
Hey thanks for this! I wrote this for a contract about a year ago and forgot that I still had the project up here on github. I didn't think anyone would be using it. I'll take a look and see if I can figure out the `UnityPause` issue.

**Comment by haxpor** [comment]
@samizzo I got it now. `UnityPause()` as of version 5 it accepts integer as parameter, but unity 4 accepts boolean. I came across some more issues that prevent unity game to get touch event as well, but I has fixed it now (might not be too clean, but it works). I will come back here and make a pull request :)

**Comment by samizzo** [comment]
Thank you very much! I didn't get around to investigating it. I'm going to merge this into my branch now. I'm going to remove the xcworkspacedata and xccheckout files though because they point to your github repo.

**Pull request merged**
